Added Smoothies and system to call the menu.
Jordan3421/SmoothieShop pull request #4
Opened 2021-03-17 20:02 UTC by sandydavidson95

Added menu system.

2021-03-17 21:03 UTC, Jordan3421 requested changes
A couple of comments on things that I would like to see done, if you could do those changes and then re commit, push and pull again.

2021-03-17 21:03 UTC, Jordan3421 commented on resource/Fruits/Smoothies.csv
> +1,Smoothie Flavours
Would like to see smoothie flavours instead of ingredients, such as Strawberry & Banana, Orange Mango & Passion fruit etc., also prices would be nice as well, such as 1, Strawberry & Banana, 3.00

2021-03-17 21:03 UTC, Jordan3421 commented on src/Display/ReadSmoothieFile.py
> +
I think it'd be beneficial if this was a class instead of just a function as it can be created in other parts of code, e.g. 

```
class Menu:
    def Smoothie_Menu(self):
        readCSVFile = ReadCSVFile()
        smoothie_Menu = readCSVFile.getFileData(ENTITIES_FOLDER, "Smoothies" + ".csv")
        return smoothie_Menu
```

2021-03-21 21:56 UTC, Jordan3421 approved these changes
Looks good - I'm happy with these changes, thanks.

2021-03-21 22:14 UTC, MillieM27 approved these changes
Had a quick look over and think the code looks good alongside Jordans feedback for changes - no further changes needed in my opinion

2021-03-21 22:17 UTC, merged